version: '3'

services:
  app:
    build: ./docker/php
    container_name: messanger-app
    volumes:
      - ./:/var/www/html
    environment:
      TZ: Asia/Tokyo

  web:
    build: ./docker/nginx
    container_name: messanger-web
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
    links:
      - app

  db:
    build: ./docker/mysql
    container_name: messanger-db
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
