version: '3'

services:
  db:
    build: ./docker/mysql
    container_name: messenger-db
    environment:
      MYSQL_DATABASE: messenger
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  app:
    build: ./docker/php
    container_name: messenger-app
    volumes:
      - ./:/var/www/html
    environment:
      TZ: Asia/Tokyo

  web:
    build: ./docker/nginx
    container_name: messenger-web
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
    links:
      - app
